In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [4]:
a = np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
print(a)

[1 2 3 4]


In [8]:
a = np.array([1,2,3,5])

In [9]:
a

array([1, 2, 3, 5])

In [10]:
print(a)

[1 2 3 5]


In [11]:
a.dtype

dtype('int32')

In [12]:
a.btype

AttributeError: 'numpy.ndarray' object has no attribute 'btype'

In [13]:
a.atype

AttributeError: 'numpy.ndarray' object has no attribute 'atype'

In [14]:
a.ndim

1

In [15]:
a.shape

(4,)

In [16]:
a.itemsize

4

In [17]:
a.tolist()

[1, 2, 3, 5]

In [18]:
c=np.array([1,2,3])

In [19]:
c

array([1, 2, 3])

In [21]:
d=np.array([1,2,3])

In [22]:
c is d

False

In [26]:
e = np.asarray(c)

In [27]:
c is e

True

In [28]:
e is c

True

In [29]:
f = c.copy()

In [30]:
f

array([1, 2, 3])

In [31]:
f is c

False

In [32]:
c is f

False

In [33]:
import pandas as pd

In [36]:
s = pd.Series([1,2,3,4], index =list('abcd'))

In [37]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [38]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [39]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [40]:
s.ndim

1

In [41]:
s.shape

(4,)

In [42]:
s.size

4

In [44]:
s.shape

(4,)

In [45]:
s['a']

1

In [46]:
s['d']

4

In [47]:
s['a':'c']

a    1
b    2
c    3
dtype: int64

In [48]:
s[:]

a    1
b    2
c    3
d    4
dtype: int64

In [49]:
s[:-1]

a    1
b    2
c    3
dtype: int64

In [52]:
df = pd.DataFrame([[1,2,3,4],[5,6,7,8]], index=list('ab'), columns=list('abcd'))

In [53]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8

In [54]:
inedx*columns

NameError: name 'inedx' is not defined

In [55]:
index*columns

NameError: name 'index' is not defined